{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: {{ include "nfs-provisioner.chart" . }}
    app.kubernetes.io/name: {{ include "nfs-provisioner.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- range $key, $value := .Values.extraLabels }}
    "{{ $key }}": "{{ $value }}"
    {{- end }}
  name: {{ include "nfs-provisioner.fullname" . }}
{{- end }}
